server:
  port: 9099
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: secondskill
    url: jdbc:mysql://localhost:3306/secondskill?characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

